# Generated by Django 3.2.9 on 2021-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='topic',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
