# Generated by Django 3.2.9 on 2021-11-19 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0002_alter_forum_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('link', models.CharField(max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='forum',
        ),
        migrations.AddField(
            model_name='doubt',
            name='tags',
            field=models.ManyToManyField(related_name='doubts', to='DoubtForum.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='doubt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubtForum.doubt'),
        ),
    ]
