# Generated by Django 3.2.9 on 2021-11-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0003_auto_20211119_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='title',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
