# Generated by Django 3.2.9 on 2021-11-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0004_auto_20211119_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
