# Generated by Django 3.2.9 on 2021-11-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0005_auto_20211119_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
