# Generated by Django 3.2.9 on 2021-11-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0006_alter_doubt_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('scheduled_for', models.DateTimeField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoubtForum.tag')),
            ],
        ),
    ]
