# Generated by Django 3.2.9 on 2021-11-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0007_doubtsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doubtsession',
            old_name='tag',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='doubtsession',
            name='link_to_session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
