# Generated by Django 3.2.9 on 2021-11-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0008_auto_20211122_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Subject',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='tags',
        ),
        migrations.AddField(
            model_name='doubt',
            name='subject',
            field=models.ManyToManyField(related_name='doubts', to='DoubtForum.Subject'),
        ),
    ]
