# Generated by Django 3.2.9 on 2021-11-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoubtForum', '0009_auto_20211122_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubt',
            name='title',
            field=models.CharField(max_length=160),
        ),
    ]
